### ISSUE TITLE
The arguments object usage

### ISSUE THREAD

**Issue by whoisbroken** [vinneras95/Class-MyAray#11]
https://github.com/vinneras95/Class-MyAray/blob/4fcfc67e539e1a89ce46d8050a0b1093b7aa2fb8/script.js#L2

Arguments is an Array-like object
Note: If you're writing ES6 compatible code, then rest parameters should be preferred.
Note: “Array-like” means that arguments has a length property and properties indexed from zero, but it doesn't have Array's built-in methods like forEach() or map().

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments

**Comment by vinneras95** [comment]
thank you my friend
