### ISSUE TITLE
Add check on undefined in if block, you can use method without callback

### ISSUE THREAD

**Issue by whoisbroken** [vinneras95/Class-MyAray#12]
https://github.com/vinneras95/Class-MyAray/blob/4fcfc67e539e1a89ce46d8050a0b1093b7aa2fb8/script.js#L96

if we call function without callback, we've got error.
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by vinneras95** [comment]
thanks, i will fix
