### ISSUE TITLE
variable declaration

### ISSUE THREAD

**Issue by whoisbroken** [vinneras95/Class-MyAray#3]
https://github.com/vinneras95/Class-MyAray/blob/585b79d63876ce66635cc09daf4cabbdf244c736/script.js#L28

A good practice is using const first for every variable declaration. Whenever you feel that you want to reassign that variable to another value, then it's time for changing to let.

you should use let if
```
let a = 5
a = 10
```
or
```
let a = [12,3]
a = ['s',23]
```
But you should better use const if
```
const a = [12,3]
a.push('s')
```
in this case a doesn't changing - it was a link to the array and it is still a link to the initial array

**Comment by vinneras95** [comment]
thank you my friend
